<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Phraseback</AssemblyName>
    <Product>Phraseback</Product>
    <Title>Phraseback</Title>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Phraseback.Tests" />
    <ProjectReference Include="../Phraseback.Client/Phraseback.Client.csproj" />
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
  </ItemGroup>
</Project>
